### ISSUE TITLE
Basic Challenge Completed

### ISSUE THREAD

**Issue by thoragio** [learn-javascript-courses/rejection#5]
Code: https://github.com/thoragio/rejection
Demo: https://thoragio.github.io/rejection/

I enjoyed working on this project. What really stumped me though was what to write tests for. I had a nice boilerplate for testing all ready to go, but in the end I built it and never could see the path for TDD during it. :-(

**Comment by ericelliott** [comment]
Nice work!

I like the UI you came up with. It's quite intuitive.

It looks to me like the reason for the TDD struggle is that there isn't really much in the way of separation of concerns. I do most of my TDD using unit tests, which are designed to test individual units -- little pieces of the app. For that to work, you need to break the code up into modules. Typically:

1. UI component modules to handle drawing stuff to the screen and listening for user inputs
2. App state modules to handle keeping track of the state of the app (the data/information/domain model)
3. Modules to handle things like communicating over the network, saving/loading data, etc...

When you separate your app in those ways, it becomes a lot more clear how to test things. Frameworks often help us answer the question of how to separate apps into those various pieces. There are an infinite number of ways you *could* separate an app (many of them valid). What frameworks do is draw the lines for us so we just need to fill in the details for our particular application.

It will take some time to learn a framework (I recommend that you [start with React](https://medium.com/javascript-scene/top-javascript-frameworks-topics-to-learn-in-2017-700a397b711)). Before you dig too deeply into that, try separating different functions from your app into different modules, and use `import` or `require()` to pull them together.

That will require you to use a build step. That can be complicated to set up, but you can skip most of the configuration if you try out [Next.js](https://github.com/zeit/next.js/), because it handles most of that for you.

**Comment by thoragio** [comment]
Thanks for the feedback, Eric. Much appreciated.

I will try refactoring the app by putting the functions into different modules as you suggest. Once I have done that, I will add in the functionality for the mid-level of the project.

Your point on frameworks/React are noted. I am headed in that direction already. Thanks again.
