### ISSUE TITLE
Mid Level Completed!

### ISSUE THREAD

**Issue by maxyzli** [learn-javascript-courses/rejection#9]
Finish Mid Level Challenge 

- [Rejection App Demo](https://rejection-okpdxtkfrd.now.sh/)
- [Github Repo](https://github.com/LIYINGZHEN/rejection/tree/mid-level)

### Stack

1. Next.js
2. React
3. Redux
4. Redux-Saga
5. Firebase
6. TDD (Tape, Cheerio, Nightwatch)

## Architecture/Pattern

1. [Ducks pattern](https://github.com/erikras/ducks-modular-redux)
2. [10 Tips for Better Redux Architecture](https://medium.com/javascript-scene/10-tips-for-better-redux-architecture-69250425af44#.da2mybyxi)
3. [Feature-based file structures](https://medium.com/@alexmngn/how-to-use-redux-on-highly-scalable-javascript-applications-4e4b8cb5ef38#.b8l08w4za)
4. [Pure Component](https://github.com/ericelliott/react-pure-component-starter)
5. [Functional setState](https://medium.com/javascript-scene/setstate-gate-abc10a9b2d82#.i19vpd88v)

## Nightwatch Demo

![2017-03-22 09 40 48](https://cloud.githubusercontent.com/assets/11765228/24179709/b8737b5c-0eeb-11e7-8019-1518f626616a.gif)

## Special thanks to

@ericelliott
@JScheerleader 
@thoragio

**Comment by ericelliott** [comment]
Great job! Here are some things I really liked:

* Good balance of unit tests vs functional tests.
  - Functional tests work great to ensure that critical happy paths are still working, and that UI buttons respond when clicked.
  - Unit tests work better to test the details and edge cases of the application domain logic.
  - Keeping fewer functional tests means that tests run faster, giving developers feedback in a tighter loop, which helps stay more productive.
* Your reducers looked very simple and easy to understand. Great work!
* Nice job with action creators. The function signatures and default assignments should give you great feedback if you have `atom-ternjs` installed (`apm install atom-ternjs`).
* Using Material UI was a wise choice. The UI looks professional!
* Good job debugging your Nightwatch setup!

Tips:

* All action types and action creators should be colocated with reducers. It doesn't make sense to duplicate them.
* Selecting and updating stuff by id is a common requirement, and can be abstracted out.
* Remember to handle loading and error states. See [redux-dsm](https://github.com/ericelliott/redux-dsm)
* You should split saga worker tasks so that each worker handles a single action response workflow.
